baseURL = "https://www.kailunli.me"
languageCode = "en-us"
title = "Kailun's Blog"
theme = "hugo-theme-m10c"

[params]
    author = "Kailun Li"
    description = "Learn. Think. Build. Connect."
    avatar = "photo.jpeg"

    [[params.social]]
        name = "github"
        url = "https://github.com/Kailun2047"
        icon = "brand-github"
    [[params.social]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/kailun-li-45892314a/"
        icon = "brand-linkedin"